(module
	(memory $mem 3000 10000)
	(export "memory" (memory $mem))
	(func (export "dwt_forward") (param $origin i32) (param $width i32) (param $height i32) (param $level i32)
        (local $ptrsucc i32)
        (local $ptr i32)
        (local $ptrpred i32)
        (local $ptrprpr i32)
        (local $inc i32)
        (local $end i32)
        (local $ih i32)
        (local $linebeg i32)
        (local.set $origin (i32.rotl (local.get $origin) (i32.const 2)))
        (local.set $linebeg (local.get $origin))
        (local.set $ih (i32.const 0))
        (block $breakimage 
        (loop $wholeimage 
        (br_if $breakimage (i32.ge_u (local.get $ih) (local.get $height)))
        (local.set $linebeg (i32.add (local.get $linebeg) (i32.rotl (local.get $width) (i32.const 2)) ) )
		(local.set $inc (i32.rotl (i32.rotl (i32.const 1) (local.get $level)) (i32.const 2)) ) 
        (local.set $end (i32.add (local.get $linebeg) (i32.rotl (local.get $width) (i32.const 2)) ))
        (local.set $ptrpred (local.get $linebeg)) 
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc))) 
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
        (if (i32.ge_u (local.get $ptrsucc) (local.get $end)) 
            (then 
                (local.get $ptr)
                (i32.sub (i32.load (local.get $ptr)) (i32.load (local.get $ptrpred))) 
                (i32.store)
                (local.get $ptrpred)
                (i32.load (local.get $ptrpred))
                (i32.shr_s (i32.add (i32.load (local.get $ptr)) (i32.const 1)) (i32.const 1)) 
                (i32.add) 
                (i32.store)
                return 
            )
        ) 
        (local.get $ptr)
        (i32.load (local.get $ptr)) 
        (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) ) 
        (i32.sub) 
        (i32.store)
        (local.get $ptrpred) 
        (i32.load (local.get $ptrpred))
        (i32.shr_s (i32.add (i32.load (local.get $ptr)) (i32.const 1)) (i32.const 1)) 
        (i32.add) 
        (i32.store)
        (local.set $ptrprpr (local.get $ptr)) 
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
        (local.set $ptrpred (local.get $ptrsucc)) 
        (local.set $ptr (i32.add (local.get $ptrsucc) (local.get $inc)) ) 
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
        (block $breakhigh 
            (loop $top
                (br_if $breakhigh (i32.ge_u (local.get $ptrsucc) (local.get $end))) 
                (local.get $ptr) 
                (i32.load (local.get $ptr)) 
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) ) 
                (i32.sub) 
                (i32.store)
                (local.get $ptrpred) 
                (i32.load (local.get $ptrpred))
                (i32.add (i32.load (local.get $ptrprpr)) (i32.load (local.get $ptr))) 
                (i32.const 2)
                (i32.add  ) 
                (i32.const 2)
                (i32.shr_s  ) 
                (i32.add) 
                (i32.store)
                (local.set $ptrprpr (local.get $ptr))
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrsucc) (local.get $inc)) ) 
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end)) 
            (then 
                (local.get $ptr)
                (i32.sub (i32.load (local.get $ptr)) (i32.load (local.get $ptrpred))) 
                (i32.store)
                (local.get $ptrpred) 
                (i32.load (local.get $ptrpred))
                (i32.add (i32.load (local.get $ptrprpr)) (i32.load (local.get $ptr))) 
                (i32.const 2)
                (i32.add  ) 
                (i32.const 2)
                (i32.shr_s  ) 
                (i32.add) 
                (i32.store)
            )
            (else 
            (if (i32.lt_u (local.get $ptrpred) (local.get $end)) 
                (then 
                    (local.get $ptrpred)
                    (i32.shr_s (i32.add (i32.load (local.get $ptrprpr)) (i32.const 1) ) (i32.const 1) ) 
                    (i32.load (local.get $ptrpred))
                    (i32.add  ) 
                    (i32.store)
                )
            )
            )
        ) 
        (local.set $ih (i32.add (local.get $ih) (i32.const 1))) 
        (br $wholeimage) 
        ) 
        ) 
	)
	(func (export "dwt_forward_vert") (param $origin i32) (param $stride i32) (param $end i32) (param $level i32)
        (local $ptrsucc i32) 
        (local $ptr i32) 
        (local $ptrpred i32) 
        (local $ptrprpr i32) 
        (local $inc i32) 
        (local.set $origin (i32.rotl (local.get $origin) (i32.const 2))) 
		(local.set $inc (i32.rotl (i32.rotl (local.get $stride) (local.get $level)) (i32.const 2)) )
        (local.set $end (i32.add (local.get $origin) (i32.rotl (local.get $end) (i32.const 2)) ) ) 
        (local.set $ptrpred (local.get $origin)) 
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc))) 
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
        (if (i32.ge_u (local.get $ptrsucc) (local.get $end)) 
            (then 
                (local.get $ptr)
                (i32.sub (i32.load (local.get $ptr)) (i32.load (local.get $ptrpred))) 
                (i32.store)
                (local.get $ptrpred)
                (i32.load (local.get $ptrpred))
                (i32.shr_s (i32.add (i32.load (local.get $ptr)) (i32.const 1)) (i32.const 1)) 
                (i32.add) 
                (i32.store)
                return 
            )
        ) 
        (local.get $ptr)
        (i32.load (local.get $ptr)) 
        (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) ) 
        (i32.sub) 
        (i32.store)
        (local.get $ptrpred) 
        (i32.load (local.get $ptrpred))
        (i32.shr_s (i32.add (i32.load (local.get $ptr)) (i32.const 1)) (i32.const 1)) 
        (i32.add) 
        (i32.store)
        (local.set $ptrprpr (local.get $ptr)) 
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
        (local.set $ptrpred (local.get $ptrsucc)) 
        (local.set $ptr (i32.add (local.get $ptrsucc) (local.get $inc)) ) 
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
        (block $breakhigh 
            (loop $top
                (br_if $breakhigh (i32.ge_u (local.get $ptrsucc) (local.get $end))) 
                (local.get $ptr) 
                (i32.load (local.get $ptr)) 
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) ) 
                (i32.sub) 
                (i32.store)
                (local.get $ptrpred) 
                (i32.load (local.get $ptrpred))
                (i32.add (i32.load (local.get $ptrprpr)) (i32.load (local.get $ptr))) 
                (i32.const 2)
                (i32.add  ) 
                (i32.const 2)
                (i32.shr_s  ) 
                (i32.add) 
                (i32.store)
                (local.set $ptrprpr (local.get $ptr))
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrsucc) (local.get $inc)) ) 
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end)) 
            (then 
                (local.get $ptr)
                (i32.sub (i32.load (local.get $ptr)) (i32.load (local.get $ptrpred))) 
                (i32.store)
                (local.get $ptrpred) 
                (i32.load (local.get $ptrpred))
                (i32.add (i32.load (local.get $ptrprpr)) (i32.load (local.get $ptr))) 
                (i32.const 2)
                (i32.add  ) 
                (i32.const 2)
                (i32.shr_s  ) 
                (i32.add) 
                (i32.store)
            )
            (else 
            (if (i32.lt_u (local.get $ptrpred) (local.get $end)) 
                (then 
                    (local.get $ptrpred)
                    (i32.shr_s (i32.add (i32.load (local.get $ptrprpr)) (i32.const 1) ) (i32.const 1) ) 
                    (i32.load (local.get $ptrpred))
                    (i32.add  ) 
                    (i32.store)
                )
            )
            )
        ) 
	)
	(func (export "dwt_inverse") (param $origin i32) (param $stride i32) (param $end i32) (param $level i32)
        (local $ptrsucc i32)
        (local $ptr i32)
        (local $ptrpred i32)
        (local $inc i32)
        (local.set $origin (i32.rotl (local.get $origin) (i32.const 2)))
		(local.set $inc (i32.rotl (i32.rotl (local.get $stride) (local.get $level)) (i32.const 2)) )
        (local.set $end (i32.add (local.get $origin) (i32.rotl (local.get $end) (i32.const 2)) ) )
        (local.set $ptr (local.get $origin))
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
        (local.get $ptr)
        (i32.load (local.get $ptr))
        (i32.shr_s (i32.load (local.get $ptrsucc)) (i32.const 1))
        (i32.sub)
        (i32.store)
        (local.set $ptrpred (local.get $ptrsucc))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breakhigh
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breakhigh (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc)))
                (i32.const 2)
                (i32.add  )
                (i32.const 2)
                (i32.shr_s  )
                (i32.sub)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.const 1) )
                (i32.const 1)
                (i32.shr_s   )
                (i32.sub )
                (i32.store)
            )
        )
        (local.set $ptrpred (local.get $origin))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breaklow
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breaklow (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) )
                (i32.add)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)                
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptr)))
                (i32.store)
            )
        )
	)
)