;; TERMS OF USE
;; This source code is subject to the terms of the MIT License. 
;; Copyright(c) 2026 Vladimir Vasilich Tregub
(module
	(memory $mem 10000)
	(export "memory" (memory $mem))
	(func (export "dwt_forward_hor") (param $origin i32) (param $width i32) (param $inc i32)
        (local $ptrsucc i32) ;; i + inc
        (local $ptr i32)     ;; i
        (local $ptrpred i32) ;; i - inc
        (local $ptrprpr i32) ;; i - 2 * inc
        (local $end i32)     ;; origin + width
        (local.set $end (i32.add (local.get $origin) (local.get $width)) )
        (local.set $ptrpred (local.get $origin)) 
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc))) 
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
        (if (i32.ge_u (local.get $ptrsucc) (local.get $end)) 
            (then 
                (local.get $ptr)
                (i32.sub (i32.load (local.get $ptr)) (i32.load (local.get $ptrpred))) 
                (i32.store)
                (local.get $ptrpred)
                (i32.load (local.get $ptrpred))
                (i32.shr_s (i32.add (i32.load (local.get $ptr)) (i32.const 1)) (i32.const 1)) 
                (i32.add) 
                (i32.store)
                return 
            )
        ) 
        (local.get $ptr)
        (i32.load (local.get $ptr)) 
        (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) ) 
        (i32.sub) 
        (i32.store)
        (local.get $ptrpred) 
        (i32.load (local.get $ptrpred))
        (i32.shr_s (i32.add (i32.load (local.get $ptr)) (i32.const 1)) (i32.const 1)) 
        (i32.add) 
        (i32.store)
        (local.set $ptrprpr (local.get $ptr)) 
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
        (local.set $ptrpred (local.get $ptrsucc)) 
        (local.set $ptr (i32.add (local.get $ptrsucc) (local.get $inc)) ) 
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
        (block $breakhigh 
            (loop $top
                (br_if $breakhigh (i32.ge_u (local.get $ptrsucc) (local.get $end))) 
                (local.get $ptr) 
                (i32.load (local.get $ptr)) 
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) ) 
                (i32.sub) 
                (i32.store)
                (local.get $ptrpred) 
                (i32.load (local.get $ptrpred))
                (i32.add (i32.load (local.get $ptrprpr)) (i32.load (local.get $ptr))) 
                (i32.const 2)
                (i32.add  ) 
                (i32.const 2)
                (i32.shr_s  ) 
                (i32.add) 
                (i32.store)
                (local.set $ptrprpr (local.get $ptr))
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrsucc) (local.get $inc)) ) 
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) ) 
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end)) 
            (then 
                (local.get $ptr)
                (i32.sub (i32.load (local.get $ptr)) (i32.load (local.get $ptrpred))) 
                (i32.store)
                (local.get $ptrpred) 
                (i32.load (local.get $ptrpred))
                (i32.add (i32.load (local.get $ptrprpr)) (i32.load (local.get $ptr))) 
                (i32.const 2)
                (i32.add  ) 
                (i32.const 2)
                (i32.shr_s  ) 
                (i32.add) 
                (i32.store)
            )
            (else 
            (if (i32.lt_u (local.get $ptrpred) (local.get $end)) 
                (then 
                    (local.get $ptrpred)
                    (i32.shr_s (i32.add (i32.load (local.get $ptrprpr)) (i32.const 1) ) (i32.const 1) ) 
                    (i32.load (local.get $ptrpred))
                    (i32.add  ) 
                    (i32.store)
                )
            )
            )
        ) 
	)
	(func (export "dwt_forward_vert_first") (param $inc i32) (param $ptrpred i32) (param $ptr i32) (param $ptrsucc i32) (param $end i32)
        (local.set $end (i32.add (local.get $ptr) (local.get $end)) )
        (block $breakline 
            (loop $top
                (br_if $breakline (i32.ge_u (local.get $ptr) (local.get $end))) 
                (local.get $ptr)
                (i32.load (local.get $ptr)) 
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) ) 
                (i32.sub) 
                (i32.store)
                (local.get $ptrpred) 
                (i32.load (local.get $ptrpred))
                (i32.shr_s (i32.add (i32.load (local.get $ptr)) (i32.const 1)) (i32.const 1)) 
                (i32.add) 
                (i32.store)
                (local.set $ptrpred (i32.add (local.get $ptrpred) (i32.const 4)))
                (local.set $ptr (i32.add (local.get $ptr) (i32.const 4)) ) 
                (local.set $ptrsucc (i32.add (local.get $ptrsucc) (i32.const 4)) )                   
                (br $top)
            )
        )
    )
	(func (export "dwt_forward_vert") (param $ptrprpr i32) (param $ptrpred i32) (param $ptr i32) (param $ptrsucc i32) (param $end i32)
        (local.set $end (i32.add (local.get $ptr) (local.get $end)) )
        (block $breakhigh 
            (loop $top
                (br_if $breakhigh (i32.ge_u (local.get $ptr) (local.get $end))) 
                (local.get $ptr) 
                (i32.load (local.get $ptr)) 
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) ) 
                (i32.sub) 
                (i32.store)
                (local.get $ptrpred) 
                (i32.load (local.get $ptrpred))
                (i32.add (i32.load (local.get $ptrprpr)) (i32.load (local.get $ptr))) 
                (i32.const 2)
                (i32.add  ) 
                (i32.const 2)
                (i32.shr_s  ) 
                (i32.add) 
                (i32.store)
                (local.set $ptrprpr (i32.add (local.get $ptrprpr) (i32.const 4)))
                (local.set $ptrpred (i32.add (local.get $ptrpred) (i32.const 4)))
                (local.set $ptr (i32.add (local.get $ptr) (i32.const 4)) ) 
                (local.set $ptrsucc (i32.add (local.get $ptrsucc) (i32.const 4)) )                   
                (br $top)
            )
        )
	)
	(func (export "dwt_forward_vert_last") (param $ptrprpr i32) (param $ptrpred i32) (param $ptr i32) (param $end i32)
        (local.set $end (i32.add (local.get $ptr) (local.get $end)) )
        (block $breakline 
            (loop $top
                (br_if $breakline (i32.ge_u (local.get $ptr) (local.get $end))) 
                (local.get $ptr)
                (i32.load (local.get $ptr))                                                     
                (i32.load (local.get $ptrpred))                                                     
                (i32.sub) 
                (i32.store)
                (local.get $ptrpred)
                (i32.load (local.get $ptrpred))
                (i32.add (i32.load (local.get $ptrprpr)) (i32.load (local.get $ptr))) 
                (i32.const 2)
                (i32.add ) 
                (i32.const 2)
                (i32.shr_s  ) 
                (i32.add) 
                (i32.store)
                (local.set $ptrprpr (i32.add (local.get $ptrprpr) (i32.const 4)) )                   
                (local.set $ptrpred (i32.add (local.get $ptrpred) (i32.const 4)))
                (local.set $ptr (i32.add (local.get $ptr) (i32.const 4)) ) 
                (br $top)
            )
        )
    )
	(func (export "dwt_forward_vert_lastelse") (param $ptrprpr i32) (param $ptrpred i32) (param $end i32)
        (local.set $end (i32.add (local.get $ptrpred) (local.get $end)) )
        (block $breakline                                                                           ;; for (iw = ($ptr); iw < ($ptr) + width8; iw += 4) {
            (loop $top
                (br_if $breakline (i32.ge_u (local.get $ptrpred) (local.get $end)))                 ;; i < width;
                (local.get $ptrpred)
                (i32.load (local.get $ptrpred))                                                     ;; im[i - inc]
                (i32.add (i32.load (local.get $ptrprpr)) (i32.const 1))                             ;; im[i - 2 * inc] + 1
                (i32.const 1)
                (i32.shr_s )
                (i32.sub)                                                                           ;; im[i - inc] -= (im[i - 2 * inc] + 1) >> 1
                (i32.store)
                (local.set $ptrprpr (i32.add (local.get $ptrprpr) (i32.const 4)))
                (local.set $ptrpred (i32.add (local.get $ptrpred) (i32.const 4)))                   ;; i += 4 
                (br $top)
            )
        )
    )
	(func (export "dwt_inverse") (param $origin i32) (param $stride i32) (param $end i32) (param $level i32)
        (local $ptrsucc i32)
        (local $ptr i32)
        (local $ptrpred i32)
        (local $inc i32)
        (local.set $origin (i32.rotl (local.get $origin) (i32.const 2)))
		(local.set $inc (i32.rotl (i32.rotl (local.get $stride) (local.get $level)) (i32.const 2)) )
        (local.set $end (i32.add (local.get $origin) (i32.rotl (local.get $end) (i32.const 2)) ) )
        (local.set $ptr (local.get $origin))
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
        (local.get $ptr)
        (i32.load (local.get $ptr))
        (i32.shr_s (i32.load (local.get $ptrsucc)) (i32.const 1))
        (i32.sub)
        (i32.store)
        (local.set $ptrpred (local.get $ptrsucc))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breakhigh
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breakhigh (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc)))
                (i32.const 2)
                (i32.add  )
                (i32.const 2)
                (i32.shr_s  )
                (i32.sub)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.const 1) )
                (i32.const 1)
                (i32.shr_s   )
                (i32.sub )
                (i32.store)
            )
        )
        (local.set $ptrpred (local.get $origin))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breaklow
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breaklow (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) )
                (i32.add)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)                
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptr)))
                (i32.store)
            )
        )
	)
)