(module
    (memory (import "js" "mem") 1)
	;; Create and export an wasm memory
	(memory $image 100)
	(export "image" (memory $image))
	(memory $xform 100)
	(export "xform" (memory $xform))

	(func (export "dwt_forward")  (param $len i32) (param $level i32)
        (local $end i32)
        (local $ptrsucc i32)
        (local $ptr i32)
        (local $ptrpred i32)
        (local $inc i32)
        (local.set $end (i32.mul (local.get $len) (i32.const 4) ) )
		(local.set $inc (i32.rotl (i32.rotl (i32.const 1) (local.get $level)) (i32.const 2)) )
        (local.set $ptrpred (i32.const 0))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breakhigh
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breakhigh (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) )
                (i32.sub)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)
                (i32.sub (i32.load (local.get $ptr)) (i32.load (local.get $ptrpred)))
                (i32.store)
            )
        )
        (local.set $ptr (i32.const 0) )
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
        (local.get $ptr)
        (i32.load (local.get $ptr))
        (i32.shr_s (i32.load (local.get $ptrsucc)) (i32.const 1))
        (i32.add)
        (i32.store)
        (local.set $ptrpred (local.get $ptrsucc))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breaklow
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breaklow (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc)))
                (i32.const 2)
                (i32.add  )
                (i32.const 2)
                (i32.shr_s  )
                (i32.add)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.const 1) ) (i32.const 1) )
                (i32.load (local.get $ptr))
                (i32.add  )
                (i32.store)
            )
        )
	)
	(func (export "dwt_inverse")  (param $len i32) (param $level i32)
        (local $end i32)
        (local $ptrsucc i32)
        (local $ptr i32)
        (local $ptrpred i32)
        (local $inc i32)
        (local.set $end (i32.mul (local.get $len) (i32.const 4) ) )
		(local.set $inc (i32.rotl (i32.rotl (i32.const 1) (local.get $level)) (i32.const 2)) )
        (local.set $ptrpred (i32.const 0))
        (local.set $ptr (i32.const 0) )
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
        (local.get $ptr)
        (i32.load (local.get $ptr))
        (i32.shr_s (i32.load (local.get $ptrsucc)) (i32.const 1))
        (i32.sub)
        (i32.store)
        (local.set $ptrpred (local.get $ptrsucc))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breakhigh
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breakhigh (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc)))
                (i32.const 2)
                (i32.add  )
                (i32.const 2)
                (i32.shr_s  )
                (i32.sub)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.const 1) )
                (i32.const 1)
                (i32.shr_s   )
                (i32.sub )
                (i32.store)
            )
        )
        (local.set $ptrpred (i32.const 0))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breaklow
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breaklow (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) )
                (i32.add)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)                
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptr)))
                (i32.store)
            )
        )
	)
)