;; TERMS OF USE
;; This source code is subject to the terms of the MIT License. 
;; Copyright(c) 2026 Vladimir Vasilich Tregub
(module
	(memory $mem 3000 10000)
	(export "memory" (memory $mem))
	(func (export "dwt_forward") (param $origin i32) (param $stride i32) (param $end i32) (param $level i32)
        (local $ptrsucc i32)
        (local $ptr i32)
        (local $ptrpred i32)
        (local $inc i32)
        (local.set $origin (i32.rotl (local.get $origin) (i32.const 2)))
		(local.set $inc (i32.rotl (i32.rotl (local.get $stride) (local.get $level)) (i32.const 2)) )
        (local.set $end (i32.add (local.get $origin) (i32.rotl (local.get $end) (i32.const 2)) ) )
        (local.set $ptrpred (local.get $origin))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breakhigh
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breakhigh (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) )
                (i32.sub)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)
                (i32.sub (i32.load (local.get $ptr)) (i32.load (local.get $ptrpred)))
                (i32.store)
            )
        )
        (local.set $ptr (local.get $origin) )
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
        (local.get $ptr)
        (i32.load (local.get $ptr))
        (i32.shr_s (i32.load (local.get $ptrsucc)) (i32.const 1))
        (i32.add)
        (i32.store)
        (local.set $ptrpred (local.get $ptrsucc))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breaklow
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breaklow (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc)))
                (i32.const 2)
                (i32.add  )
                (i32.const 2)
                (i32.shr_s  )
                (i32.add)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.const 1) ) (i32.const 1) )
                (i32.load (local.get $ptr))
                (i32.add  )
                (i32.store)
            )
        )
	)
	(func (export "dwt_inverse") (param $origin i32) (param $stride i32) (param $end i32) (param $level i32)
        (local $ptrsucc i32)
        (local $ptr i32)
        (local $ptrpred i32)
        (local $inc i32)
        (local.set $origin (i32.rotl (local.get $origin) (i32.const 2)))
		(local.set $inc (i32.rotl (i32.rotl (local.get $stride) (local.get $level)) (i32.const 2)) )
        (local.set $end (i32.add (local.get $origin) (i32.rotl (local.get $end) (i32.const 2)) ) )
        (local.set $ptr (local.get $origin))
        (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
        (local.get $ptr)
        (i32.load (local.get $ptr))
        (i32.shr_s (i32.load (local.get $ptrsucc)) (i32.const 1))
        (i32.sub)
        (i32.store)
        (local.set $ptrpred (local.get $ptrsucc))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breakhigh
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breakhigh (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc)))
                (i32.const 2)
                (i32.add  )
                (i32.const 2)
                (i32.shr_s  )
                (i32.sub)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.add (i32.load (local.get $ptrpred)) (i32.const 1) )
                (i32.const 1)
                (i32.shr_s   )
                (i32.sub )
                (i32.store)
            )
        )
        (local.set $ptrpred (local.get $origin))
        (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)))
        (block $breaklow
            (loop $top
                (local.set $ptrsucc (i32.add (local.get $ptr) (local.get $inc)) )
                (br_if $breaklow (i32.ge_u (local.get $ptrsucc) (local.get $end)))
                (local.get $ptr)
                (i32.load (local.get $ptr))
                (i32.shr_s (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptrsucc))) (i32.const 1) )
                (i32.add)
                (i32.store)
                (local.set $ptrpred (local.get $ptrsucc))
                (local.set $ptr (i32.add (local.get $ptrpred) (local.get $inc)) )
                (br $top)
            )
        )
        (if (i32.lt_u (local.get $ptr) (local.get $end))
            (then 
                (local.get $ptr)                
                (i32.add (i32.load (local.get $ptrpred)) (i32.load (local.get $ptr)))
                (i32.store)
            )
        )
	)
)